# Link
main.exe: main.o sinewave.o squarewave.o
	g++ -o main.exe main.o sinewave.o squarewave.o

# Compile
main.o: main.cpp
	g++ -c main.cpp

sinewave.o: sinewave.cpp
	g++ -c sinewave.cpp

squarewave.o: squarewave.cpp
	g++ -c squarewave.cpp
