# Link
main.exe: main.o instrument.o percussion.o pitched.o
	g++ -o main.exe main.o instrument.o percussion.o pitched.o

# Compile
main.o: main.cpp
	g++ -c main.cpp

instrument.o: instrument.cpp
	g++ -c instrument.cpp

percussion.o: percussion.cpp
	g++ -c percussion.cpp

pitched.o: pitched.cpp
	g++ -c pitched.cpp
